### ISSUE TITLE
Failed to install dependencies

### ISSUE THREAD

**Issue by Sherww** [Jaynil1611/syn-qg#6]
Hi,
I try to run the command **"pip install ."**, but I meet the error.

>  Using cached moses-0.9.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda3\envs\py36\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\njdx\\AppData\\Local\\Temp\\pip-install-g3otbqwd\\moses_3dfeb2f4e9864d73b834f5cfbc249cc4\\setup.py'"'"'; __file__='"'"'C:\\Users\\njdx\\AppData\\Local\\Temp\\pip-install-g3otbqwd\\moses_3dfeb2f4e9864d73b834f5cfbc249cc4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\njdx\AppData\Local\Temp\pip-pip-egg-info-twdb3ody'
         cwd: C:\Users\njdx\AppData\Local\Temp\pip-install-g3otbqwd\moses_3dfeb2f4e9864d73b834f5cfbc249cc4\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\njdx\AppData\Local\Temp\pip-install-g3otbqwd\moses_3dfeb2f4e9864d73b834f5cfbc249cc4\setup.py", line 33, in <module>
        long_description=load_description('README.rst'),
      File "C:\Users\njdx\AppData\Local\Temp\pip-install-g3otbqwd\moses_3dfeb2f4e9864d73b834f5cfbc249cc4\setup.py", line 12, in load_description
        return f.read().strip()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 21: illegal multibyte sequence
WARNING: Discarding https://files.pythonhosted.org/packages/25/46/d2cc5c0ed87633cb566bbe8a30a296dc3363daf0b4095b45c126be84bb27/moses-0.9.0.tar.gz#sha256=113f2b4668fc1b2ef59fce64ec85c9fe251363437b2bf15029744840284d929d (from https://pypi.org/simple/moses/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
**ERROR: Could not find a version that satisfies the requirement moses (from allennlp) (from versions: 0.9.0, 0.10.0)
ERROR: No matching distribution found for moses**

This seems to be due to the version of the package, then I try to run the command **"python setup.py install"**, but I meet another error.
 It seems like I can not install fastBPE.

> Installed d:\anaconda3\envs\py36\lib\site-packages\allennlp-0.8.2_unreleased-py3.6.egg
Processing dependencies for allennlp===0.8.2-unreleased
Searching for fastBPE==0.1.0
Reading https://pypi.org/simple/fastBPE/
Downloading https://files.pythonhosted.org/packages/e1/37/f97181428a5d151501b90b2cebedf97c81b034ace753606a3cda5ad4e6e2/fastBPE-0.1.0.tar.gz#sha256=95eef4be2689e822a918ac4eae3349cd78ca3f28af591afa421f8fac6d4cd889
Best match: fastBPE 0.1.0
Processing fastBPE-0.1.0.tar.gz
Writing C:\Users\njdx\AppData\Local\Temp\easy_install-oilelwsg\fastBPE-0.1.0\setup.cfg
Running fastBPE-0.1.0\setup.py -q bdist_egg --dist-dir C:\Users\njdx\AppData\Local\Temp\easy_install-oilelwsg\fastBPE-0.1.0\egg-dist-tmp-i3gw15m3
package init file 'fastBPE\__init__.py' not found (or not a regular file)
cl: 命令行 warning D9025 :正在重写“/Os”(用“/Ot”)
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
cl: 命令行 warning D9002 :忽略未知选项“-Of”
cl: 命令行 warning D9002 :忽略未知选项“-Oa”
cl: 命令行 warning D9002 :忽略未知选项“-pthread”
fastBPE.cpp
C:\Users\njdx\AppData\Local\Temp\easy_install-oilelwsg\fastBPE-0.1.0\fastBPE\fastBPE.hpp(15): fatal error C1083: 无法打 开包括文件: “sys/mman.h”: No such file or directory
**error: Setup script exited with error: command 'D:\\visualstudio_all\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2**

**This is my environment:** Python 3.6.13; system: Windows 10. 
Thanks for your reply!

**Comment by Sherww** [comment]
I changed the system to Linux and the above problems were solved.
